# Variables available to all templates via .<key>
# Surface common data into templates
[packages.darwin]
brew = [
    "git",
    "nushell",
    "ripgrep",
    "fd",
    "fzf",
    "starship",
    "mise",
    "zsh-autosuggestions",
    "bat",
    "jandedobbeleer/oh-my-posh/oh-my-posh",
    "fish",
    "gemini",
    "git-delta",
    "tmux",
    "zoxide",
    "gemini-cli",
    "dotenv",
    "gnupg",
    "direnv",
    "gnu-tar",
    "wget",
]
casks = [
    "iterm2",
    "visual-studio-code",
    "raycast",
    # "google-chrome",
    "linear-linear",
    "cursor",
    "telegram-desktop",
    "discord",
    "spotify",
    # "1password",
    "font-sauce-code-pro-nerd-font",
    "claude-code",
]

[packages.linux]
apt = [
    "build-essential",
    "clang",
    "curl",
    "direnv",
    "fd-find",
    "fzf",
    "git",
    "git-delta",
    "gpg",
    "mdadm",
    "ripgrep",
    "tmux",
    "unzip",
    "wget",
    "zoxide",
    "zsh",
    "zsh-autosuggestions",
    "mise",
]
